MOVIE_DB_API_KEY = "6e59753c154de03e426cf6b18175566d"
MOVIE_DB_SEARCH_URL = f"https://api.themoviedb.org/3/search/movie?query=Jack+Reacher&api_key={MOVIE_DB_API_KEY}"
# MOVIE_DB_IMAGE_URL = "https://api.themoviedb.org/3/movie/550"
MOVIE_DB_IMAGE_URL = "https://image.tmdb.org/t/p/original/"
MOVIE_DB_INFO_URL = "https://api.themoviedb.org/3/movie/343611?api_key=API_KEY"